environment = "test"
resource_group_name = "RG-ExamAzureFunctions"
location = "SouthEast Asia"
open_api_spec_content_format = "openapi+json"
open_api_spec_content_value = "https://exampleazfuncservicebus.azurewebsites.net/api/swagger.json"